version: '3.8'

services:
  # ✅ Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "neura_sync"
      DB_USER: "postgres"
      DB_PASSWORD: "secure_password"
    depends_on:
      - db
      - redis

  # ✅ Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # ✅ PostgreSQL Database
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: neura_sync
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ✅ Redis for Caching
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
