# Use Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy frontend files
COPY . .

# Build frontend
RUN yarn build

# Serve frontend using lightweight server
EXPOSE 3000
CMD ["yarn", "start"]
