apiVersion: v1
kind: ConfigMap
metadata:
  name: neura-sync-config
  namespace: neura-sync
  labels:
    app: neura-sync
data:
  BACKEND_PORT: "8000"
  FRONTEND_PORT: "3000"
  POSTGRES_HOST: "neura-sync-postgres-svc"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "neura-sync-redis-svc"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
  API_VERSION: "v1"
  JWT_EXPIRATION_MINUTES: "60"
  NODE_ENV: "production"
  CLUSTER_MODE: "true"
  K8S_NAMESPACE: "neura-sync"
