apiVersion: apps/v1
kind: Deployment
metadata:
  name: neura-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neura-backend
  template:
    metadata:
      labels:
        app: neura-backend
    spec:
      containers:
      - name: backend
        image: neura-sync-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "db-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "secure_password"
        - name: DB_NAME
          value: "neura_sync"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
