apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neura-sync-backend-hpa
  namespace: neura-sync
  labels:
    app: neura-sync-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neura-sync-backend
  minReplicas: 3                     # Minimum backend pods
  maxReplicas: 10                    # Maximum backend pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70     # Scale out at 70% CPU usage
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75     # Scale out at 75% memory usage
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neura-sync-frontend-hpa
  namespace: neura-sync
  labels:
    app: neura-sync-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neura-sync-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65
