apiVersion: v1
kind: Secret
metadata:
  name: neura-sync-secrets
  namespace: neura-sync
  labels:
    app: neura-sync
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=                 # Base64 encoded: postgres
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk      # Base64 encoded: secure_password
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=         # Base64 encoded: redis_password
  JWT_SECRET: c3VwZXJfc2VjcmV0                # Base64 encoded: super_secret
